name: Plan
on:
  pull_request:
    branches:
      - qa
      - master
      - staging

# jobs:
#   requirements-backend:
#     uses: ${change-it-for-your-tribe-pipeline}
#     with:
#       project-name: 'bbog-dig-dt-nodejs-mngr-template'
#       project-key: 'bbog-dig-dt-nodejs-mngr-template'
#       language: 'javascript'
#       node-version: '18.x'
#       service-type: 'lambda'
#       service-name: 'lambda-resource-name'
#       test-command: >
#         npm run test
#       path-environments-variables: >
#         pipeline/qa-env.json
#         pipeline/stg-env.json
#         pipeline/prod-env.json
#     secrets: inherit
