name: Deploy Rollback
on:
  workflow_dispatch:
    inputs:
      rollback-version:
        description: "Please, enter the pre version lambda to execute rollback"
        required: true
      environment:
        description: "Please, enter the environment"
        required: true
        type: choice
        options:
        - pr
        - st
        - qa
env:
  lambda-function-name: "${include-your-function-name}"
  aws-region: "us-east-1"
jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Action Lambda
        uses: actions/checkout@v3
        with:
          repository: bancodebogota/bdb-dig-do-pipelines-action-lambdas-IaC
          ref: 'v3'
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/bdb-dig-do-pipelines-action-lambdas-IaC
      - name: Rollback Lambda
        uses: ./.github/actions/bdb-dig-do-pipelines-action-lambdas-IaC/rollback
        with:
          function-name: ${{ env.lambda-function-name }}
          rollback-version: ${{ inputs.rollback-version }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          role-assume: ${{ secrets.AWS_ROLE_DEPLOY_BACKEND }}
          aws-region: ${{ env.aws-region }}
